name: load-tests

on:
  workflow_dispatch:
    inputs:
      api_url:
        description: "URL of service to run tests"
        required: true
        type: string
      request_threshold:
        description: "Request Threshold to test (p(95)<1500)"
        required: true
        type: string
      request_count:
        description: "Request count to test (count < 15)"
        required: true
        type: string

jobs:
  k6_cloud_test:
    name: k6 cloud test run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: k6 Load Test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load_test.js
          flags: -e API_URL=${{inputs.api_url}} -e REQUEST_THRESHOLD="${{inputs.request_threshold}}" -e REQUEST_COUNT="${{inputs.request_count}}"

      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: result.html
